### ISSUE TITLE
Add ability to execute command(s) when countdown is over

### ISSUE THREAD

**Issue by schlundd** [StreamController/Countdown#1]
It would be great if the plugin would let me add a command that runs as soon as the countdown is over, so I could have it play a sound or display a notification.

These could also be dedicated settings (play sound / show notifcation), but running command(s) is probably the most flexible and maybe the quickest to implement.

**Comment by Core447** [comment]
You can (already) do this using the "Delay" action of the OS plugin, by using the following layout:

1. Delay action (set to eg 5 seconds)
2. Run command action

**Comment by schlundd** [comment]
But then this action would run anytime I press the button (i.e. also when I press to pause the countdown), wouldn't it?

**Comment by Core447** [comment]
Yeah... I can add a command option

**Comment by Core447** [comment]
Added with 37e5936171fb836fa32a79b69c9a610db7a43663

**Comment by schlundd** [comment]
Perfect, thanks!
